language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V --toolchains .m2/travis-ci-toolchains.xml

branches:
  only:
    - master
