language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"

before_install:
  - rm ~/.m2/settings.xml
  - mvn verify --toolchains .m2/travis-ci-toolchains.xml
  - openssl aes-256-cbc -K $encrypted_dacfc0476f3d_key -iv $encrypted_dacfc0476f3d_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
  - chmod 600 ~/.ssh/id_rsa_travis
  - echo -e "Host 35.236.128.26\n\tStrictHostKeyChecking no\n\tIdentityFile
    ~/.ssh/id_rsa_travis" >> ~/.ssh/config
addons:
  ssh_known_hosts: 35.236.128.26

install: true
script:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V --toolchains .m2/travis-ci-toolchains.xml
after_script:
  - bash .travis/deploy.sh
