language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V --toolchains .m2/travis-ci-toolchains.xml

jobs:
  include:
    # 1.1 Semver check
    - stage: test
      jdk: openjdk11
      script: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true --toolchains .m2/travis-ci-toolchains.xml
      env: CHECK_SEMANTIC_VERSION=true

branches:
  only:
    - master
